### ISSUE TITLE
Repurposing the wptrainingteam GH organisation 

### ISSUE THREAD

**Issue by jonathanbossenger** [wptrainingteam/wptrainingteam.github.io#66] opened 2023-05-10 06:09 UTC
**What?**

Members of the WordPress community have been looking for a place to house all code examples used for Learn WordPress and the Core Developer Blog. You can read about this request [here](https://github.com/WordPress/Learn/issues/1509#issuecomment-1518985453).

It has been suggested and mostly agreed upon to repurpose the https://github.com/wptrainingteam/ organization for this purpose.

**How?**

1. Invite specific community team members and project leadership to join this organization as owners. To start with, the following folks could be added: @webtechpooja and @bsanevans ( as team reps of the Training Team), @bph (as the team rep for the core dev blog), and @josephahaden (executive director of the WordPress project). Other owners can be added later as needed.
2. Rename the organization to something other than `wptrainingteam`. This new name can be discussed amongst the updated organization owners. 
3. Review all open code repositories in the organization, with a view to marking them as [archived](https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories). Marking them as archived will retain the repositories and their history, but make it read-only for all users and indicate that it's no longer actively maintained.
4. Review and update the https://github.com/wptrainingteam/wptrainingteam.github.io repository to match the new organisation name and purpose.
5. Decide on a process for how WordPress contributors will be added to this organisation, in order to upload their example code repositories.

**Comment by jonathanbossenger** [comment] 2023-05-10 06:10
Tagging @courtneyr-dev on this conversation, we may need your help inviting new owners.

**Comment by jonathanbossenger** [comment] 2023-05-11 10:34
@courtneyr-dev would you be able to start the process by elevating @webtechpooja to owner status?

**Comment by jonathanbossenger** [comment] 2023-06-08 13:03
Thank you @courtneyr-dev for upgrading our team reps, @webtechpooja, @bsanevans and @piyopiyo-kitsune as owners of this organization.

**Comment by jonathanbossenger** [comment] 2023-06-08 13:03
@bsanevans or @webtechpooja a next step, can we please invite @josephahaden and @bph as owners of the organization as well.

At the same time, can we look at renaming the organization from wptrainingteam to learn-wordpress.

**Comment by kaitohm** [comment] 2023-06-09 00:24
@josephahaden and @bph have both been invited as owners of this organization 👍 

For the moment, I've updated the organization display name to `Learn WordPress`. I've also changed the billing email from a Gmail address to a WordPress.org address the Training Team has access to in Help Scout.

I can also rename the organization, but would just like a nod from another couple of owners before I do so.

**Comment by Piyopiyo-Kitsune** [comment] 2023-06-09 01:35
Access confirmed-- thank you for getting this set up @jonathanbossenger @courtneyr-dev! I think it would be super helpful to start drafting a handbook page on how to engage with this repo/org going forward which we can link in the description.

**Comment by jonathanbossenger** [comment] 2023-06-09 11:13
> I think it would be super helpful to start drafting a handbook page on how to engage with this repo/org going forward which we can link in the description.

@Piyopiyo-Kitsune agreed, but @bph, @courtneyr-dev, and I also chatted about the fact that this doc shouldn't live with the training team handbook exclusively, as we might want this GH organization to be made available to all make teams/team reps who need to host code examples for educational/training purposes. 

So it was suggested that we create a readme.md file in a code repository in this organisation, and then link to it from our respective team handbooks. My plan is to work on this when I get back next week.

**Comment by courtneyr-dev** [comment] 2023-06-26 20:14
Agreed @jonathanbossenger on the readme.md approach. Can we also include a contribute.md file that drives people to any teams using this? 

Also noting for historical purposes, we want to preserve the content that Training team worked on for many years before we could access LearnWP.

**Comment by bph** [comment] 2023-07-27 11:13
Howdy, howdy. Huge thank you to everyone in this thread for moving forward with the discussion on how to admin this organization and accommodate various make teams producing educational content

If that's ok with you, I would like to start a test project with one of the most prolific writers on the WordPress Developer Blog, Justin Tadlock (github handle: @justintadlock) He is working on [part 2 of his  Beyond Block Styles](https://github.com/WordPress/developer-blog-content/issues/152) series and could use a repo to house the example code, which you can [view on his personal GitHub account here](https://github.com/justintadlock/beyond-block-styles/branches)

Going through onboarding Justin would give us enough process experience to form opinions and focus on what's important for writers, reviewers, and admins on the Developer Blog Editorial group. 

What do you think?

**Comment by justintadlock** [comment] 2023-07-27 12:40
I'm happy to be the tester for this from the Dev Blog side of things. As @bph said, I'm currently in the middle of a three-part tutorial series that has a lot of code examples, so this would be an ideal time to test. Currently, there is no way for readers to see the code as a whole without me linking to my personal GH account, something we'd rather avoid.

**Comment by jonathanbossenger** [comment] 2023-07-28 09:42
I think this is a great idea, and will help us define the process for how we allow access to folks for adding their repos to this Organization. 

All I ask is that we document the steps you all take to make this happen so that we could turn this into a handbook document somewhere. 

Feel free to ping me if you need any help or have any questions on anything.

**Comment by bph** [comment] 2023-07-31 10:16
Fabulous! We'll discuss process and documents along the way on the issue [#133](https://github.com/WordPress/developer-blog-content/issues/133) on the Developer Blog Content space.

**Comment by justintadlock** [comment] 2023-08-02 22:27
I have transferred ownership of the [Beyond Block Styles](https://github.com/wptrainingteam/beyond-block-styles) repo as a first test.

I don't really have any notes at this time since I simply just did a straight transfer from my personal account to this org. I'll still need to go through the process of linking to it within the Dev Blog posts.

**Comment by jonathanbossenger** [comment] 2023-11-30 09:20
@bph I feel like the original purpose of this issue has been accomplished now. Do you think we can close this?

**Comment by bph** [comment] 2023-11-30 09:56
Yes, this has been completed. Closing now. And activity on this organization now also reflected on contributors' wordpress.org profiles ([meta trac 7355](https://meta.trac.wordpress.org/ticket/7355))

**Closed as completed by bph** 2023-11-30 09:56 UTC
